#!/bin/bash

source /etc/default/clusterctrl
let "PIZERO_OFFSET = (4 * ${CLUSTERHAT_NUMBER}) - 4"

if [ $# -eq 0 ]
then
    OPTIONS=" "
    for PIZEROSTATE in `clusterctrl status | tail -n 4`
    do
        PIZERO_RAW="${PIZEROSTATE:1:1}"
	let "PIZERO = ${PIZERO_RAW} + ${PIZERO_OFFSET}"
        PIZERO_STATUS="${PIZEROSTATE:3:1}"
        if [ "$PIZERO_STATUS" == "1" ]; then
            OPTIONS+="$PIZERO on "
        else
            OPTIONS+="$PIZERO off "
        fi
    done

    cmd=(dialog --stdout --no-items --nocancel --separate-output --ok-label "Turn PiZeros on/off" --checklist "clusterhat ${CLUSTERHAT_NUMBER} PiZeros" 12 10 10)
    TURN=$("${cmd[@]}" ${OPTIONS})

    if [ "$?" != 0 ]
    then
        exit
    fi
else 
    TURN=`ls /etc/clusterhat/on/`
fi

echo
for PIZERO_RAW in 1 2 3 4
do
    let PIZERO=$PIZERO_RAW+$PIZERO_OFFSET
    echo -n "#$PIZERO_RAW: p$PIZERO "
    if [[ $TURN == *"${PIZERO}"* ]]; then
        clusterctrl on p${PIZERO_RAW}
        touch /etc/clusterhat/on/$PIZERO
        rm -f /etc/clusterhat/off/$PIZERO
        echo " on"
    else 
        clusterctrl off p${PIZERO_RAW}
        touch /etc/clusterhat/off/$PIZERO
        rm -f /etc/clusterhat/on/$PIZERO
        echo " off"
    fi
done
