.\" Manpage for chtui
.\" Contact: Vítězslav Dvořák <your.email@example.com>
.TH CHTUI 1 "September 2021" "chtui 1.0" "chtui man page"

.SH NAME
chtui \- ncurses Cluster HAT TUI tool

.SH SYNOPSIS
.B chtui
[\fIOPTION\fR]...

.SH DESCRIPTION
chtui is a command-line tool that provides a text-based user interface (TUI) for managing the Cluster HAT.

.SH OPTIONS
.TP
\fB-h, --help\fR
Display help message and exit.

.TP
\fB-v, --version\fR
Display version information and exit.

.SH EXAMPLES
.TP
To start chtui:
.BR chtui

.SH SEE ALSO
.TP
The Cluster HAT website: \fIhttps://clusterhat.com/\fR

.SH AUTHOR
Written by Vítězslav Dvořák.

.SH COPYRIGHT
Copyright \(co 2024 Vítězslav Dvořák.

.SH BUGS
Report bugs to: Vítězslav Dvořák <info@vitexsoftware.cz>
